import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Check, Crown, Sparkles, Zap, ArrowRight } from 'lucide-react';
import SectionHeading from '../components/SectionHeading';

const tiers = [
  {
    name: 'Growth',
    commission: '20%',
    icon: Zap,
    color: 'from-primary/20 to-primary/5',
    borderColor: 'border-primary/20 hover:border-primary/40',
    features: [
      'Comprehensive marketing strategy, built from scratch for your brand',
      'Contractual 3x income guarantee within your first 30 days',
      'Full message and DM management — handled with precision 24/7',
      'In-depth personality profiling and bespoke persona development',
      'Genuine, fluid conversations crafted to mirror your natural voice',
      'Emotional loyalty architecture to convert followers into devoted fans',
      'Strategically timed daily PPV campaign pushes for maximum revenue',
    ]
  },
  {
    name: 'Premium',
    commission: '30%',
    icon: Crown,
    popular: true,
    color: 'from-secondary/20 to-accent/10',
    borderColor: 'border-secondary/30 hover:border-secondary/50',
    features: [
      'Every deliverable from the Growth tier, flawlessly executed',
      'Professional content creation support and ideation on demand',
      'AI-assisted content generation to keep your feed consistently elite',
      'Never run dry — we ensure a relentless flow of high-quality content',
      'Advanced posting cadence and strategic scheduling optimization',
      'Subscriber reactivation campaigns to recover lost revenue',
      'Priority-tier team access with accelerated response times',
    ]
  },
  {
    name: 'Elite',
    commission: '40%',
    icon: Sparkles,
    color: 'from-accent/20 to-primary/10',
    borderColor: 'border-accent/30 hover:border-accent/50',
    features: [
      'The complete arsenal from both the Growth and Premium tiers',
      'Weekly private 1-on-1 coaching and strategy sessions',
      'Direct, unrestricted access to our CEO for high-level guidance',
      'Up to 75% of your content fully generated by our creative team',
      'All we require: your startup photos and videos — we handle the rest',
      'Custom niche architecture engineered to match live market demand',
      'A fully hands-off, done-for-you empire management experience',
    ]
  }
];

export default function Services() {
  const servicesImg = 'https://media.base44.com/images/public/69dcf9f1af90480281ca6ada/069426b76_generated_498d01f4.png';

  return (
    <div>
      <section className="relative py-20 md:py-32 overflow-hidden">
        <div className="absolute inset-0">
          <img src={servicesImg} alt="Elite Services" className="w-full h-full object-cover opacity-20" />
          <div className="absolute inset-0 bg-gradient-to-b from-background via-background/80 to-background" />
        </div>
        
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <SectionHeading
            badge="Our Services"
            title={<>Commission-Based <span className="text-primary">Mastery</span></>}
            subtitle="Every tier is architected around one non-negotiable principle: your income must grow. From personality engineering to full content generation, our commission-based model means we only win when you win — and we intend to win at the highest possible level."
          />

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 md:gap-8">
            {tiers.map((tier, i) => (
              <motion.div
                key={tier.name}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15, duration: 0.6 }}
                className={`relative rounded-2xl bg-gradient-to-b ${tier.color} border ${tier.borderColor} p-6 md:p-8 transition-all duration-500 flex flex-col`}
              >
                {tier.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 bg-secondary text-secondary-foreground text-xs font-display font-bold rounded-full uppercase tracking-wider">
                    Most Selected
                  </div>
                )}

                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-card flex items-center justify-center">
                    <tier.icon className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-display font-bold text-xl text-foreground">{tier.name}</h3>
                    <p className="text-xs text-muted-foreground font-body">Tier</p>
                  </div>
                </div>

                <div className="mb-6">
                  <span className="font-serif text-5xl font-bold text-foreground">{tier.commission}</span>
                  <span className="text-muted-foreground font-body ml-1">commission</span>
                </div>

                <ul className="space-y-3 mb-8 flex-1">
                  {tier.features.map(f => (
                    <li key={f} className="flex items-start gap-2.5">
                      <Check className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                      <span className="text-sm text-muted-foreground font-body">{f}</span>
                    </li>
                  ))}
                </ul>

                <Link
                  to="/apply"
                  className="group flex items-center justify-center gap-2 w-full py-3.5 font-display font-bold text-sm rounded-lg transition-all hover:scale-105"
                  style={{ background: '#74F0ED', color: '#000' }}
                >
                  Begin Your Ascent <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </Link>
              </motion.div>
            ))}
          </div>

          <div className="mt-16 text-center">
            <p className="text-muted-foreground font-body text-sm max-w-xl mx-auto">
              Unsure which tier aligns with your ambitions? Apply and our strategy team will personally guide you to the plan that maximizes your trajectory — no pressure, no pitch, just honest expert counsel.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}